version: '2'

services:
  crawler:
    image: pidcheck_crawler
    build:
      context: .
      dockerfile: docker/crawler/Dockerfile
    depends_on:
      - redis
    restart: always

  redis:
    image: redis
    ports:
      - "6379"
    restart: always