version: '2'

services:
  crawler:
    image: datacite/pidcheck-crawler
    build:
      context: .
      dockerfile: docker/crawler/Dockerfile
    depends_on:
      - redis
    restart: always
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always